# -*- coding: utf-8 -*-
"""Supply-Chain-Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108q1syTaTAcL3qCwhL-u5zACRGcbZdEO

## 1.UPLOAD TEXT FILE
"""

from google.colab import files
uploaded=files.upload()

"""## 2.CONVERT TEXT FILE INTO CSV FILE"""

import pandas as pd

# Load the file
df = pd.read_csv("cost_new.txt", skip_blank_lines=True)

# Save it as a clean, properly formatted CSV
df.to_csv("cost_clean.csv", index=False)

"""## 3.DATA UNDERSTANDING"""

# load the data frame
df

# Rows and Columns of the data set
df.shape

# Find if null
df.isna().sum()

## Statistical information
df.describe()

## Find the data types of the data
df.info()

"""## Statistics"""

df

"""## Distribution Graphs"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style='whitegrid')
fig, axes=plt.subplots(1,2,figsize=(14,5))

sns.regplot(ax=axes[0],data=df,x='distance_to_farm_km',y='wastage_kg',color='crimson')
axes[0].set_title('Impact of Distance on raw material wastage')

sns.scatterplot(ax=axes[1],data=df,x='employees_count',y='productivity',hue='plant_location', s=100)
axes[1].set_title('Impact of employees count on productivity')

plt.tight_layout()
plt.show()

"""# graph_1
# distance_to_farm_km vs wastage_kg

## graph_2

## employees_count vs productivity

## 4.DATA PREPARATION/FEATURE ENGINEERING
"""

df_copy=df.copy()

list=['id','farm_location','plant_lon','plant_lat','farm_lat','farm_lon']

df_cleaned=df_copy.drop(columns=list,axis=1,)

df_cleaned

df_prepared=pd.get_dummies(df_cleaned,columns=['plant_location'],drop_first=False)

# change the boolean values into 1 and 0
for col in df_prepared.columns:
  if df_prepared[col].dtype=='bool':
    df_prepared[col]=df_prepared[col].astype(int)
print("Prepared data columns:",df_prepared.columns.tolist())

"""## 5.MODEL BUILDING"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
#TARGET COLUMNS
target_cols=['productivity','wastage_kg','return_sales_ml']

x=df_prepared.drop(columns=target_cols,axis=1)
y=df_prepared[target_cols]

"""## TRAIN TEST SPLIT DATA

"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# control the sample size
base_model=RandomForestRegressor(n_estimators=15,max_depth=3,random_state=42)

"""## 6.MODEL TRAINING"""

multi_output_model=base_model.fit(x_train,y_train)
print('The model was trained succsessfully')

"""## 7.MODEL EVALUATION"""

from sklearn.metrics import mean_absolute_error,r2_score
y_pred=multi_output_model.predict(x_test)
y_pred_df=pd.DataFrame(y_pred,columns=target_cols,index=y_test.index)

print('MODEL OUTPUTS')

for target in target_cols:
  mae=mean_absolute_error(y_test[target],y_pred_df[target])
  r2=r2_score(y_test[target],y_pred_df[target])
  print(f"OUTPUT: {target:<18} | mae: {mae: <8.3f} |r : {r2: .3f}")

"""## 8,MODEL DEPLOYEMENT"""

import joblib
## saving the model
model_filename='multi_output_model.pkl'

joblib.dump(multi_output_model,model_filename)
print(f"saved name :{model_filename}")

## load the model
loaded_model=joblib.load(model_filename)
## Mock production input
# [plant_cost,distance_to_farm_km,employees_count,input_kg,output_ml,ingredients_cost,sales_ml,plant_location_Gampaha,plant_location_Kandy,plant_location_Matara]
mock_production_input = [[140000,3.5,22,480,390000,11500,370000,1,0,0]]

predictions=loaded_model.predict(mock_production_input)
print("PREDICTION FOR THE SPECIFIC OUTPUT")
print(f"productivity:   {predictions[0][0]:2f}")
print(f"Wastage:   {predictions[0][1] :2f}kg")
print(f"Return ml:   {predictions[0][2]:2f}ml")

